// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/mobile-otp/mobile-otp.proto

package otpgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdType int32

const (
	IdType_ID_TYPE_UNKNOWN IdType = 0
	IdType_ID_TYPE_NUMERIC IdType = 1
	IdType_ID_TYPE_UUID    IdType = 2
)

// Enum value maps for IdType.
var (
	IdType_name = map[int32]string{
		0: "ID_TYPE_UNKNOWN",
		1: "ID_TYPE_NUMERIC",
		2: "ID_TYPE_UUID",
	}
	IdType_value = map[string]int32{
		"ID_TYPE_UNKNOWN": 0,
		"ID_TYPE_NUMERIC": 1,
		"ID_TYPE_UUID":    2,
	}
)

func (x IdType) Enum() *IdType {
	p := new(IdType)
	*p = x
	return p
}

func (x IdType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_mobile_otp_mobile_otp_proto_enumTypes[0].Descriptor()
}

func (IdType) Type() protoreflect.EnumType {
	return &file_api_mobile_otp_mobile_otp_proto_enumTypes[0]
}

func (x IdType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdType.Descriptor instead.
func (IdType) EnumDescriptor() ([]byte, []int) {
	return file_api_mobile_otp_mobile_otp_proto_rawDescGZIP(), []int{0}
}

type ID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          IdType                 `protobuf:"varint,1,opt,name=type,proto3,enum=mobile.otpgrpc.IdType" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ID) Reset() {
	*x = ID{}
	mi := &file_api_mobile_otp_mobile_otp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ID) ProtoMessage() {}

func (x *ID) ProtoReflect() protoreflect.Message {
	mi := &file_api_mobile_otp_mobile_otp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ID.ProtoReflect.Descriptor instead.
func (*ID) Descriptor() ([]byte, []int) {
	return file_api_mobile_otp_mobile_otp_proto_rawDescGZIP(), []int{0}
}

func (x *ID) GetType() IdType {
	if x != nil {
		return x.Type
	}
	return IdType_ID_TYPE_UNKNOWN
}

func (x *ID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OTP) Reset() {
	*x = OTP{}
	mi := &file_api_mobile_otp_mobile_otp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OTP) ProtoMessage() {}

func (x *OTP) ProtoReflect() protoreflect.Message {
	mi := &file_api_mobile_otp_mobile_otp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OTP.ProtoReflect.Descriptor instead.
func (*OTP) Descriptor() ([]byte, []int) {
	return file_api_mobile_otp_mobile_otp_proto_rawDescGZIP(), []int{1}
}

func (x *OTP) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type CreateOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *ID                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOTPRequest) Reset() {
	*x = CreateOTPRequest{}
	mi := &file_api_mobile_otp_mobile_otp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOTPRequest) ProtoMessage() {}

func (x *CreateOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mobile_otp_mobile_otp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOTPRequest.ProtoReflect.Descriptor instead.
func (*CreateOTPRequest) Descriptor() ([]byte, []int) {
	return file_api_mobile_otp_mobile_otp_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOTPRequest) GetId() *ID {
	if x != nil {
		return x.Id
	}
	return nil
}

type CreateOTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOTPResponse) Reset() {
	*x = CreateOTPResponse{}
	mi := &file_api_mobile_otp_mobile_otp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOTPResponse) ProtoMessage() {}

func (x *CreateOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mobile_otp_mobile_otp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOTPResponse.ProtoReflect.Descriptor instead.
func (*CreateOTPResponse) Descriptor() ([]byte, []int) {
	return file_api_mobile_otp_mobile_otp_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOTPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CheckOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *ID                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Otp           *OTP                   `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckOTPRequest) Reset() {
	*x = CheckOTPRequest{}
	mi := &file_api_mobile_otp_mobile_otp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOTPRequest) ProtoMessage() {}

func (x *CheckOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mobile_otp_mobile_otp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOTPRequest.ProtoReflect.Descriptor instead.
func (*CheckOTPRequest) Descriptor() ([]byte, []int) {
	return file_api_mobile_otp_mobile_otp_proto_rawDescGZIP(), []int{4}
}

func (x *CheckOTPRequest) GetId() *ID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CheckOTPRequest) GetOtp() *OTP {
	if x != nil {
		return x.Otp
	}
	return nil
}

type CheckOTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckOTPResponse) Reset() {
	*x = CheckOTPResponse{}
	mi := &file_api_mobile_otp_mobile_otp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOTPResponse) ProtoMessage() {}

func (x *CheckOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mobile_otp_mobile_otp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOTPResponse.ProtoReflect.Descriptor instead.
func (*CheckOTPResponse) Descriptor() ([]byte, []int) {
	return file_api_mobile_otp_mobile_otp_proto_rawDescGZIP(), []int{5}
}

func (x *CheckOTPResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_api_mobile_otp_mobile_otp_proto protoreflect.FileDescriptor

const file_api_mobile_otp_mobile_otp_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/mobile-otp/mobile-otp.proto\x12\x0emobile.otpgrpc\"@\n" +
	"\x02ID\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.mobile.otpgrpc.IdTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x19\n" +
	"\x03OTP\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\"6\n" +
	"\x10CreateOTPRequest\x12\"\n" +
	"\x02id\x18\x01 \x01(\v2\x12.mobile.otpgrpc.IDR\x02id\"-\n" +
	"\x11CreateOTPResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\\\n" +
	"\x0fCheckOTPRequest\x12\"\n" +
	"\x02id\x18\x01 \x01(\v2\x12.mobile.otpgrpc.IDR\x02id\x12%\n" +
	"\x03otp\x18\x02 \x01(\v2\x13.mobile.otpgrpc.OTPR\x03otp\"\"\n" +
	"\x10CheckOTPResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok*D\n" +
	"\x06IdType\x12\x13\n" +
	"\x0fID_TYPE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fID_TYPE_NUMERIC\x10\x01\x12\x10\n" +
	"\fID_TYPE_UUID\x10\x022\xb0\x01\n" +
	"\tMobileOTP\x12R\n" +
	"\tCreateOTP\x12 .mobile.otpgrpc.CreateOTPRequest\x1a!.mobile.otpgrpc.CreateOTPResponse\"\x00\x12O\n" +
	"\bCheckOTP\x12\x1f.mobile.otpgrpc.CheckOTPRequest\x1a .mobile.otpgrpc.CheckOTPResponse\"\x00B5Z3github.com/PluT00/mobile-otp/api/mobile-otp;otpgrpcb\x06proto3"

var (
	file_api_mobile_otp_mobile_otp_proto_rawDescOnce sync.Once
	file_api_mobile_otp_mobile_otp_proto_rawDescData []byte
)

func file_api_mobile_otp_mobile_otp_proto_rawDescGZIP() []byte {
	file_api_mobile_otp_mobile_otp_proto_rawDescOnce.Do(func() {
		file_api_mobile_otp_mobile_otp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_mobile_otp_mobile_otp_proto_rawDesc), len(file_api_mobile_otp_mobile_otp_proto_rawDesc)))
	})
	return file_api_mobile_otp_mobile_otp_proto_rawDescData
}

var file_api_mobile_otp_mobile_otp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_mobile_otp_mobile_otp_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_mobile_otp_mobile_otp_proto_goTypes = []any{
	(IdType)(0),               // 0: mobile.otpgrpc.IdType
	(*ID)(nil),                // 1: mobile.otpgrpc.ID
	(*OTP)(nil),               // 2: mobile.otpgrpc.OTP
	(*CreateOTPRequest)(nil),  // 3: mobile.otpgrpc.CreateOTPRequest
	(*CreateOTPResponse)(nil), // 4: mobile.otpgrpc.CreateOTPResponse
	(*CheckOTPRequest)(nil),   // 5: mobile.otpgrpc.CheckOTPRequest
	(*CheckOTPResponse)(nil),  // 6: mobile.otpgrpc.CheckOTPResponse
}
var file_api_mobile_otp_mobile_otp_proto_depIdxs = []int32{
	0, // 0: mobile.otpgrpc.ID.type:type_name -> mobile.otpgrpc.IdType
	1, // 1: mobile.otpgrpc.CreateOTPRequest.id:type_name -> mobile.otpgrpc.ID
	1, // 2: mobile.otpgrpc.CheckOTPRequest.id:type_name -> mobile.otpgrpc.ID
	2, // 3: mobile.otpgrpc.CheckOTPRequest.otp:type_name -> mobile.otpgrpc.OTP
	3, // 4: mobile.otpgrpc.MobileOTP.CreateOTP:input_type -> mobile.otpgrpc.CreateOTPRequest
	5, // 5: mobile.otpgrpc.MobileOTP.CheckOTP:input_type -> mobile.otpgrpc.CheckOTPRequest
	4, // 6: mobile.otpgrpc.MobileOTP.CreateOTP:output_type -> mobile.otpgrpc.CreateOTPResponse
	6, // 7: mobile.otpgrpc.MobileOTP.CheckOTP:output_type -> mobile.otpgrpc.CheckOTPResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_mobile_otp_mobile_otp_proto_init() }
func file_api_mobile_otp_mobile_otp_proto_init() {
	if File_api_mobile_otp_mobile_otp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_mobile_otp_mobile_otp_proto_rawDesc), len(file_api_mobile_otp_mobile_otp_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_mobile_otp_mobile_otp_proto_goTypes,
		DependencyIndexes: file_api_mobile_otp_mobile_otp_proto_depIdxs,
		EnumInfos:         file_api_mobile_otp_mobile_otp_proto_enumTypes,
		MessageInfos:      file_api_mobile_otp_mobile_otp_proto_msgTypes,
	}.Build()
	File_api_mobile_otp_mobile_otp_proto = out.File
	file_api_mobile_otp_mobile_otp_proto_goTypes = nil
	file_api_mobile_otp_mobile_otp_proto_depIdxs = nil
}
