// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/mobile-otp/mobile-otp.proto

package otpgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OTP) Reset() {
	*x = OTP{}
	mi := &file_api_mobile_otp_mobile_otp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OTP) ProtoMessage() {}

func (x *OTP) ProtoReflect() protoreflect.Message {
	mi := &file_api_mobile_otp_mobile_otp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OTP.ProtoReflect.Descriptor instead.
func (*OTP) Descriptor() ([]byte, []int) {
	return file_api_mobile_otp_mobile_otp_proto_rawDescGZIP(), []int{0}
}

func (x *OTP) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type CreateOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOTPRequest) Reset() {
	*x = CreateOTPRequest{}
	mi := &file_api_mobile_otp_mobile_otp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOTPRequest) ProtoMessage() {}

func (x *CreateOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mobile_otp_mobile_otp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOTPRequest.ProtoReflect.Descriptor instead.
func (*CreateOTPRequest) Descriptor() ([]byte, []int) {
	return file_api_mobile_otp_mobile_otp_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOTPRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateOTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOTPResponse) Reset() {
	*x = CreateOTPResponse{}
	mi := &file_api_mobile_otp_mobile_otp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOTPResponse) ProtoMessage() {}

func (x *CreateOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mobile_otp_mobile_otp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOTPResponse.ProtoReflect.Descriptor instead.
func (*CreateOTPResponse) Descriptor() ([]byte, []int) {
	return file_api_mobile_otp_mobile_otp_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOTPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CheckOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Otp           *OTP                   `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckOTPRequest) Reset() {
	*x = CheckOTPRequest{}
	mi := &file_api_mobile_otp_mobile_otp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOTPRequest) ProtoMessage() {}

func (x *CheckOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mobile_otp_mobile_otp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOTPRequest.ProtoReflect.Descriptor instead.
func (*CheckOTPRequest) Descriptor() ([]byte, []int) {
	return file_api_mobile_otp_mobile_otp_proto_rawDescGZIP(), []int{3}
}

func (x *CheckOTPRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CheckOTPRequest) GetOtp() *OTP {
	if x != nil {
		return x.Otp
	}
	return nil
}

type CheckOTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckOTPResponse) Reset() {
	*x = CheckOTPResponse{}
	mi := &file_api_mobile_otp_mobile_otp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOTPResponse) ProtoMessage() {}

func (x *CheckOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mobile_otp_mobile_otp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOTPResponse.ProtoReflect.Descriptor instead.
func (*CheckOTPResponse) Descriptor() ([]byte, []int) {
	return file_api_mobile_otp_mobile_otp_proto_rawDescGZIP(), []int{4}
}

func (x *CheckOTPResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_api_mobile_otp_mobile_otp_proto protoreflect.FileDescriptor

const file_api_mobile_otp_mobile_otp_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/mobile-otp/mobile-otp.proto\x12\x0emobile.otpgrpc\"\x19\n" +
	"\x03OTP\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\"\"\n" +
	"\x10CreateOTPRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x11CreateOTPResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"H\n" +
	"\x0fCheckOTPRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x03otp\x18\x02 \x01(\v2\x13.mobile.otpgrpc.OTPR\x03otp\"\"\n" +
	"\x10CheckOTPResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xb0\x01\n" +
	"\tMobileOTP\x12R\n" +
	"\tCreateOTP\x12 .mobile.otpgrpc.CreateOTPRequest\x1a!.mobile.otpgrpc.CreateOTPResponse\"\x00\x12O\n" +
	"\bCheckOTP\x12\x1f.mobile.otpgrpc.CheckOTPRequest\x1a .mobile.otpgrpc.CheckOTPResponse\"\x00B5Z3github.com/PluT00/mobile-otp/api/mobile-otp;otpgrpcb\x06proto3"

var (
	file_api_mobile_otp_mobile_otp_proto_rawDescOnce sync.Once
	file_api_mobile_otp_mobile_otp_proto_rawDescData []byte
)

func file_api_mobile_otp_mobile_otp_proto_rawDescGZIP() []byte {
	file_api_mobile_otp_mobile_otp_proto_rawDescOnce.Do(func() {
		file_api_mobile_otp_mobile_otp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_mobile_otp_mobile_otp_proto_rawDesc), len(file_api_mobile_otp_mobile_otp_proto_rawDesc)))
	})
	return file_api_mobile_otp_mobile_otp_proto_rawDescData
}

var file_api_mobile_otp_mobile_otp_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_mobile_otp_mobile_otp_proto_goTypes = []any{
	(*OTP)(nil),               // 0: mobile.otpgrpc.OTP
	(*CreateOTPRequest)(nil),  // 1: mobile.otpgrpc.CreateOTPRequest
	(*CreateOTPResponse)(nil), // 2: mobile.otpgrpc.CreateOTPResponse
	(*CheckOTPRequest)(nil),   // 3: mobile.otpgrpc.CheckOTPRequest
	(*CheckOTPResponse)(nil),  // 4: mobile.otpgrpc.CheckOTPResponse
}
var file_api_mobile_otp_mobile_otp_proto_depIdxs = []int32{
	0, // 0: mobile.otpgrpc.CheckOTPRequest.otp:type_name -> mobile.otpgrpc.OTP
	1, // 1: mobile.otpgrpc.MobileOTP.CreateOTP:input_type -> mobile.otpgrpc.CreateOTPRequest
	3, // 2: mobile.otpgrpc.MobileOTP.CheckOTP:input_type -> mobile.otpgrpc.CheckOTPRequest
	2, // 3: mobile.otpgrpc.MobileOTP.CreateOTP:output_type -> mobile.otpgrpc.CreateOTPResponse
	4, // 4: mobile.otpgrpc.MobileOTP.CheckOTP:output_type -> mobile.otpgrpc.CheckOTPResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_mobile_otp_mobile_otp_proto_init() }
func file_api_mobile_otp_mobile_otp_proto_init() {
	if File_api_mobile_otp_mobile_otp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_mobile_otp_mobile_otp_proto_rawDesc), len(file_api_mobile_otp_mobile_otp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_mobile_otp_mobile_otp_proto_goTypes,
		DependencyIndexes: file_api_mobile_otp_mobile_otp_proto_depIdxs,
		MessageInfos:      file_api_mobile_otp_mobile_otp_proto_msgTypes,
	}.Build()
	File_api_mobile_otp_mobile_otp_proto = out.File
	file_api_mobile_otp_mobile_otp_proto_goTypes = nil
	file_api_mobile_otp_mobile_otp_proto_depIdxs = nil
}
