services:
  postgres:
    container_name: postgres-auth
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - auth_network
  auth-back:
    container_name: auth
    build: .
    restart: always
    ports:
      - "0.0.0.0:8081:8081"
    working_dir: /app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - auth_network

volumes:
  auth_pgdata:
networks:
  auth_network:
    driver: bridge