// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: mobile-otp/mobile-otp.proto

package otpgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MobileOTP_GetOTP_FullMethodName      = "/mobile.otpgrpc.MobileOTP/GetOTP"
	MobileOTP_NeedOTP_FullMethodName     = "/mobile.otpgrpc.MobileOTP/NeedOTP"
	MobileOTP_ValidateOTP_FullMethodName = "/mobile.otpgrpc.MobileOTP/ValidateOTP"
)

// MobileOTPClient is the client API for MobileOTP service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MobileOTPClient interface {
	// GetOTP - запрос на генерацию и отправку OTP клиенту
	GetOTP(ctx context.Context, in *GetOTPRequest, opts ...grpc.CallOption) (*GetOTPResponse, error)
	// NeedOTP - запрос на создание "заявки" на генерацию OTP при запросе определенным пользователем
	NeedOTP(ctx context.Context, in *NeedOTPRequest, opts ...grpc.CallOption) (*NeedOTPResponse, error)
	// ValidateOTP - запрос на проверку правильности OTP кода, присланного основным сервисом
	ValidateOTP(ctx context.Context, in *ValidateOTPRequest, opts ...grpc.CallOption) (*ValidateOTPResponse, error)
}

type mobileOTPClient struct {
	cc grpc.ClientConnInterface
}

func NewMobileOTPClient(cc grpc.ClientConnInterface) MobileOTPClient {
	return &mobileOTPClient{cc}
}

func (c *mobileOTPClient) GetOTP(ctx context.Context, in *GetOTPRequest, opts ...grpc.CallOption) (*GetOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOTPResponse)
	err := c.cc.Invoke(ctx, MobileOTP_GetOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mobileOTPClient) NeedOTP(ctx context.Context, in *NeedOTPRequest, opts ...grpc.CallOption) (*NeedOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NeedOTPResponse)
	err := c.cc.Invoke(ctx, MobileOTP_NeedOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mobileOTPClient) ValidateOTP(ctx context.Context, in *ValidateOTPRequest, opts ...grpc.CallOption) (*ValidateOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateOTPResponse)
	err := c.cc.Invoke(ctx, MobileOTP_ValidateOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MobileOTPServer is the server API for MobileOTP service.
// All implementations must embed UnimplementedMobileOTPServer
// for forward compatibility.
type MobileOTPServer interface {
	// GetOTP - запрос на генерацию и отправку OTP клиенту
	GetOTP(context.Context, *GetOTPRequest) (*GetOTPResponse, error)
	// NeedOTP - запрос на создание "заявки" на генерацию OTP при запросе определенным пользователем
	NeedOTP(context.Context, *NeedOTPRequest) (*NeedOTPResponse, error)
	// ValidateOTP - запрос на проверку правильности OTP кода, присланного основным сервисом
	ValidateOTP(context.Context, *ValidateOTPRequest) (*ValidateOTPResponse, error)
	mustEmbedUnimplementedMobileOTPServer()
}

// UnimplementedMobileOTPServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMobileOTPServer struct{}

func (UnimplementedMobileOTPServer) GetOTP(context.Context, *GetOTPRequest) (*GetOTPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOTP not implemented")
}
func (UnimplementedMobileOTPServer) NeedOTP(context.Context, *NeedOTPRequest) (*NeedOTPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NeedOTP not implemented")
}
func (UnimplementedMobileOTPServer) ValidateOTP(context.Context, *ValidateOTPRequest) (*ValidateOTPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateOTP not implemented")
}
func (UnimplementedMobileOTPServer) mustEmbedUnimplementedMobileOTPServer() {}
func (UnimplementedMobileOTPServer) testEmbeddedByValue()                   {}

// UnsafeMobileOTPServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MobileOTPServer will
// result in compilation errors.
type UnsafeMobileOTPServer interface {
	mustEmbedUnimplementedMobileOTPServer()
}

func RegisterMobileOTPServer(s grpc.ServiceRegistrar, srv MobileOTPServer) {
	// If the following call pancis, it indicates UnimplementedMobileOTPServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MobileOTP_ServiceDesc, srv)
}

func _MobileOTP_GetOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobileOTPServer).GetOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MobileOTP_GetOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobileOTPServer).GetOTP(ctx, req.(*GetOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MobileOTP_NeedOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NeedOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobileOTPServer).NeedOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MobileOTP_NeedOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobileOTPServer).NeedOTP(ctx, req.(*NeedOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MobileOTP_ValidateOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobileOTPServer).ValidateOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MobileOTP_ValidateOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobileOTPServer).ValidateOTP(ctx, req.(*ValidateOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MobileOTP_ServiceDesc is the grpc.ServiceDesc for MobileOTP service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MobileOTP_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mobile.otpgrpc.MobileOTP",
	HandlerType: (*MobileOTPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOTP",
			Handler:    _MobileOTP_GetOTP_Handler,
		},
		{
			MethodName: "NeedOTP",
			Handler:    _MobileOTP_NeedOTP_Handler,
		},
		{
			MethodName: "ValidateOTP",
			Handler:    _MobileOTP_ValidateOTP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mobile-otp/mobile-otp.proto",
}
