// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: mobile-otp/mobile-otp.proto

package otpgrpc

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OTP) Reset() {
	*x = OTP{}
	mi := &file_mobile_otp_mobile_otp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OTP) ProtoMessage() {}

func (x *OTP) ProtoReflect() protoreflect.Message {
	mi := &file_mobile_otp_mobile_otp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OTP.ProtoReflect.Descriptor instead.
func (*OTP) Descriptor() ([]byte, []int) {
	return file_mobile_otp_mobile_otp_proto_rawDescGZIP(), []int{0}
}

func (x *OTP) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type NeedOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeedOTPRequest) Reset() {
	*x = NeedOTPRequest{}
	mi := &file_mobile_otp_mobile_otp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeedOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeedOTPRequest) ProtoMessage() {}

func (x *NeedOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mobile_otp_mobile_otp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeedOTPRequest.ProtoReflect.Descriptor instead.
func (*NeedOTPRequest) Descriptor() ([]byte, []int) {
	return file_mobile_otp_mobile_otp_proto_rawDescGZIP(), []int{1}
}

func (x *NeedOTPRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type NeedOTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeedOTPResponse) Reset() {
	*x = NeedOTPResponse{}
	mi := &file_mobile_otp_mobile_otp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeedOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeedOTPResponse) ProtoMessage() {}

func (x *NeedOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mobile_otp_mobile_otp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeedOTPResponse.ProtoReflect.Descriptor instead.
func (*NeedOTPResponse) Descriptor() ([]byte, []int) {
	return file_mobile_otp_mobile_otp_proto_rawDescGZIP(), []int{2}
}

func (x *NeedOTPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ValidateOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Otp           *OTP                   `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateOTPRequest) Reset() {
	*x = ValidateOTPRequest{}
	mi := &file_mobile_otp_mobile_otp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateOTPRequest) ProtoMessage() {}

func (x *ValidateOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mobile_otp_mobile_otp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateOTPRequest.ProtoReflect.Descriptor instead.
func (*ValidateOTPRequest) Descriptor() ([]byte, []int) {
	return file_mobile_otp_mobile_otp_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateOTPRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ValidateOTPRequest) GetOtp() *OTP {
	if x != nil {
		return x.Otp
	}
	return nil
}

type ValidateOTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateOTPResponse) Reset() {
	*x = ValidateOTPResponse{}
	mi := &file_mobile_otp_mobile_otp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateOTPResponse) ProtoMessage() {}

func (x *ValidateOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mobile_otp_mobile_otp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateOTPResponse.ProtoReflect.Descriptor instead.
func (*ValidateOTPResponse) Descriptor() ([]byte, []int) {
	return file_mobile_otp_mobile_otp_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateOTPResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SyncKeysRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client public key (Base64)
	PublicKey string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Random number to find public key later in GetOTP request
	Nonce         int32 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncKeysRequest) Reset() {
	*x = SyncKeysRequest{}
	mi := &file_mobile_otp_mobile_otp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncKeysRequest) ProtoMessage() {}

func (x *SyncKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mobile_otp_mobile_otp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncKeysRequest.ProtoReflect.Descriptor instead.
func (*SyncKeysRequest) Descriptor() ([]byte, []int) {
	return file_mobile_otp_mobile_otp_proto_rawDescGZIP(), []int{5}
}

func (x *SyncKeysRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *SyncKeysRequest) GetNonce() int32 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type SyncKeysResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server public key (Base64)
	PublicKey     string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncKeysResponse) Reset() {
	*x = SyncKeysResponse{}
	mi := &file_mobile_otp_mobile_otp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncKeysResponse) ProtoMessage() {}

func (x *SyncKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mobile_otp_mobile_otp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncKeysResponse.ProtoReflect.Descriptor instead.
func (*SyncKeysResponse) Descriptor() ([]byte, []int) {
	return file_mobile_otp_mobile_otp_proto_rawDescGZIP(), []int{6}
}

func (x *SyncKeysResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type GetOTPRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Encrypted JWT, must be with mobile=true flag
	EncryptedJwt string `protobuf:"bytes,1,opt,name=encrypted_jwt,json=encryptedJwt,proto3" json:"encrypted_jwt,omitempty"`
	// Random number sent previously in SyncKeys request
	Nonce         int32 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOTPRequest) Reset() {
	*x = GetOTPRequest{}
	mi := &file_mobile_otp_mobile_otp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOTPRequest) ProtoMessage() {}

func (x *GetOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mobile_otp_mobile_otp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOTPRequest.ProtoReflect.Descriptor instead.
func (*GetOTPRequest) Descriptor() ([]byte, []int) {
	return file_mobile_otp_mobile_otp_proto_rawDescGZIP(), []int{7}
}

func (x *GetOTPRequest) GetEncryptedJwt() string {
	if x != nil {
		return x.EncryptedJwt
	}
	return ""
}

func (x *GetOTPRequest) GetNonce() int32 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type GetOTPResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Encrypted OTP (Base64)
	EncryptedOtp string `protobuf:"bytes,1,opt,name=encrypted_otp,json=encryptedOtp,proto3" json:"encrypted_otp,omitempty"`
	// Success flag; false if there is no request to generate OTP for that user
	Success       bool `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOTPResponse) Reset() {
	*x = GetOTPResponse{}
	mi := &file_mobile_otp_mobile_otp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOTPResponse) ProtoMessage() {}

func (x *GetOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mobile_otp_mobile_otp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOTPResponse.ProtoReflect.Descriptor instead.
func (*GetOTPResponse) Descriptor() ([]byte, []int) {
	return file_mobile_otp_mobile_otp_proto_rawDescGZIP(), []int{8}
}

func (x *GetOTPResponse) GetEncryptedOtp() string {
	if x != nil {
		return x.EncryptedOtp
	}
	return ""
}

func (x *GetOTPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_mobile_otp_mobile_otp_proto protoreflect.FileDescriptor

const file_mobile_otp_mobile_otp_proto_rawDesc = "" +
	"\n" +
	"\x1bmobile-otp/mobile-otp.proto\x12\x0emobile.otpgrpc\x1a\x1cgoogle/api/annotations.proto\"\x19\n" +
	"\x03OTP\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\" \n" +
	"\x0eNeedOTPRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x0fNeedOTPResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"K\n" +
	"\x12ValidateOTPRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x03otp\x18\x02 \x01(\v2\x13.mobile.otpgrpc.OTPR\x03otp\"%\n" +
	"\x13ValidateOTPResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"F\n" +
	"\x0fSyncKeysRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x05R\x05nonce\"1\n" +
	"\x10SyncKeysResponse\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\"J\n" +
	"\rGetOTPRequest\x12#\n" +
	"\rencrypted_jwt\x18\x01 \x01(\tR\fencryptedJwt\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x05R\x05nonce\"O\n" +
	"\x0eGetOTPResponse\x12#\n" +
	"\rencrypted_otp\x18\x01 \x01(\tR\fencryptedOtp\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess2\xf7\x02\n" +
	"\tMobileOTP\x12d\n" +
	"\bSyncKeys\x12\x1f.mobile.otpgrpc.SyncKeysRequest\x1a .mobile.otpgrpc.SyncKeysResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/sync-keys\x12\\\n" +
	"\x06GetOTP\x12\x1d.mobile.otpgrpc.GetOTPRequest\x1a\x1e.mobile.otpgrpc.GetOTPResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/get-otp\x12L\n" +
	"\aNeedOTP\x12\x1e.mobile.otpgrpc.NeedOTPRequest\x1a\x1f.mobile.otpgrpc.NeedOTPResponse\"\x00\x12X\n" +
	"\vValidateOTP\x12\".mobile.otpgrpc.ValidateOTPRequest\x1a#.mobile.otpgrpc.ValidateOTPResponse\"\x00B5Z3github.com/PluT00/mobile-otp/api/mobile-otp;otpgrpcb\x06proto3"

var (
	file_mobile_otp_mobile_otp_proto_rawDescOnce sync.Once
	file_mobile_otp_mobile_otp_proto_rawDescData []byte
)

func file_mobile_otp_mobile_otp_proto_rawDescGZIP() []byte {
	file_mobile_otp_mobile_otp_proto_rawDescOnce.Do(func() {
		file_mobile_otp_mobile_otp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mobile_otp_mobile_otp_proto_rawDesc), len(file_mobile_otp_mobile_otp_proto_rawDesc)))
	})
	return file_mobile_otp_mobile_otp_proto_rawDescData
}

var file_mobile_otp_mobile_otp_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_mobile_otp_mobile_otp_proto_goTypes = []any{
	(*OTP)(nil),                 // 0: mobile.otpgrpc.OTP
	(*NeedOTPRequest)(nil),      // 1: mobile.otpgrpc.NeedOTPRequest
	(*NeedOTPResponse)(nil),     // 2: mobile.otpgrpc.NeedOTPResponse
	(*ValidateOTPRequest)(nil),  // 3: mobile.otpgrpc.ValidateOTPRequest
	(*ValidateOTPResponse)(nil), // 4: mobile.otpgrpc.ValidateOTPResponse
	(*SyncKeysRequest)(nil),     // 5: mobile.otpgrpc.SyncKeysRequest
	(*SyncKeysResponse)(nil),    // 6: mobile.otpgrpc.SyncKeysResponse
	(*GetOTPRequest)(nil),       // 7: mobile.otpgrpc.GetOTPRequest
	(*GetOTPResponse)(nil),      // 8: mobile.otpgrpc.GetOTPResponse
}
var file_mobile_otp_mobile_otp_proto_depIdxs = []int32{
	0, // 0: mobile.otpgrpc.ValidateOTPRequest.otp:type_name -> mobile.otpgrpc.OTP
	5, // 1: mobile.otpgrpc.MobileOTP.SyncKeys:input_type -> mobile.otpgrpc.SyncKeysRequest
	7, // 2: mobile.otpgrpc.MobileOTP.GetOTP:input_type -> mobile.otpgrpc.GetOTPRequest
	1, // 3: mobile.otpgrpc.MobileOTP.NeedOTP:input_type -> mobile.otpgrpc.NeedOTPRequest
	3, // 4: mobile.otpgrpc.MobileOTP.ValidateOTP:input_type -> mobile.otpgrpc.ValidateOTPRequest
	6, // 5: mobile.otpgrpc.MobileOTP.SyncKeys:output_type -> mobile.otpgrpc.SyncKeysResponse
	8, // 6: mobile.otpgrpc.MobileOTP.GetOTP:output_type -> mobile.otpgrpc.GetOTPResponse
	2, // 7: mobile.otpgrpc.MobileOTP.NeedOTP:output_type -> mobile.otpgrpc.NeedOTPResponse
	4, // 8: mobile.otpgrpc.MobileOTP.ValidateOTP:output_type -> mobile.otpgrpc.ValidateOTPResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mobile_otp_mobile_otp_proto_init() }
func file_mobile_otp_mobile_otp_proto_init() {
	if File_mobile_otp_mobile_otp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mobile_otp_mobile_otp_proto_rawDesc), len(file_mobile_otp_mobile_otp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mobile_otp_mobile_otp_proto_goTypes,
		DependencyIndexes: file_mobile_otp_mobile_otp_proto_depIdxs,
		MessageInfos:      file_mobile_otp_mobile_otp_proto_msgTypes,
	}.Build()
	File_mobile_otp_mobile_otp_proto = out.File
	file_mobile_otp_mobile_otp_proto_goTypes = nil
	file_mobile_otp_mobile_otp_proto_depIdxs = nil
}
